### ISSUE TITLE
List element still has a selectedFg color even when all inputs are disabled.

### ISSUE THREAD

**Issue by chevex** [chjj/blessed#103]
Maybe I'm just unaware of an option and missed it while scouring the documentation, but I can't seem to figure out how to use a list element in a readonly manner. I can disable the `keys`, `input`, and `mouse` properties which seem to work fine, but I can't ever seem to get rid of the styling on the first item in the list (the default selected item).

I set `selectedFg` and `selectedBg` to the same colors as `fg` and `bg`, but I'm using ANSI escape codes to color some special characters in my list. For some reason on the selected item only, my escape codes are being overridden.

![image](https://cloud.githubusercontent.com/assets/874394/6095222/2ae1dcfa-af0e-11e4-9afe-b2c34330b0eb.png)

You can see the first list item's status icon is green where the rest are red. Note however that the ANSI bold escape sequence is still working. Only the color seems to be overridden.

Here is my code for the list:

```javascript
blessed.list({
  selectedFg: 'green',
  selectedBg: 'black',
  fg: 'green',
  keys: false,
  mouse: false,
  input: false
});
```

**Comment by chjj** [comment]
This horrible workaround will probably work for now: `list._isList = true;`.

I never thought of a non-interactive list to be honest. I can add that as an option.

**Comment by chevex** [comment]
I believe these lines [here](https://github.com/chjj/blessed/blob/master/lib/widget.js#L3338-L3343) are responsible, but I'm not having an easy time understanding what [line 3341](https://github.com/chjj/blessed/blob/master/lib/widget.js#L3341) is doing or how best to modify blessed so I can remove the selected item styling.

**Comment by chevex** [comment]
That would be a great option. If I could set something like `readonly: true` that would be awesome :)

**Comment by chjj** [comment]
That should be `list._isList = false;`.*

**Comment by chevex** [comment]
No worries, I figured it was a typo ;)

**Comment by chevex** [comment]
That is a gross hack for sure, but it worked :D

**Comment by chjj** [comment]
Also, try not to use selectedFg/Bg anymore. Those are deprecated. Try: `style: { selected: { fg: 'green' } }`. I want to eventually remove the old Fg/Bg options.

**Comment by chevex** [comment]
Good call. I agree with that move. I think a good first step would be to remove them from the docs. That's the only reason I started using them :)
