### ISSUE TITLE
Multiple screens?

### ISSUE THREAD

**Issue by chevex** [chjj/blessed#104]
I'm trying to use blessed to build a somewhat robust application. I assumed the screen objects were something I could create multiple of and attach different components to different screens and render the appropriate screen at will. Then I'd have multiple interfaces I can render, each with their own focus stack.

It seems that if I create more than one screen and try to render any of them except the first one, I get an error.

![image](https://cloud.githubusercontent.com/assets/874394/6109829/f1064b32-b03a-11e4-9a66-aeef45b07e6b.png)

If I comment out the creation of the first screen then suddenly the second screen will render without errors. I am able to call `render` on the first screen I create, even if I create a bunch more of them right after. I just can't render any screens except for the first one.

Maybe I'm not using the blessed screen as it was intended. If so, how would you recommend I go about creating a decently sized app with various interface screens? For instance, if I have two interfaces with a very different set of components, how can I easily tuck one interface away and show the other one? Do I just have to manually toggle all the displayed components to hidden, then show all the components I want? I can do that, but I want to make sure there isn't a more official way to do what I need first.

**Comment by chjj** [comment]
I haven't thought of a use for multiple screens yet. What I would recommend is a wrapper element. Just a box:

```
blessed.box({
  parent: screen,
  left: 0,
  top: 0,
  right: 0,
  bottom: 0
});
```

And make everything a child of that. You could have as many wrappers as you want. Attach and detach them as necessary. Would this work?

**Comment by chevex** [comment]
That works great and is indeed what I started doing as a backup plan. I'll continue down that path. Just wanted to make sure I'm following your conventions and not re-inventing the wheel anywhere :)

Thanks!

**Comment by chjj** [comment]
@chevex, see #157. Lots of improvements have been made.

**Comment by chevex** [comment]
@chjj Woot! Thanks for taking the time to come update me. Very much appreciated.
