### ISSUE TITLE
style.border doesn't appear to work and setting fg/bg on the border option itself applies globally

### ISSUE THREAD

**Issue by chevex** [chjj/blessed#105]
I've tried to style my borders in boxes and in a list using `style.border.fg` and `style.border.bg` but they don't appear to have any effect.

I can get it to work if I set it on the `border` option instead of the `style.border` option.

```javascript
var box = blessed.box({
  border: {
    type: 'line',
    fg: '#ffffff',  // works
    bg: '#111111'  // works
  },
  style: {
    border: {
      fg: '#ffffff', // doesn't work
      bg: '#111111', // doesn't work
    }
  }
});
```

This isn't a huge deal except for the fact that modifying the border color of another element, modifies it for all elements. I created a box element and added a list element to it. When I change the list element's border color, it changes the box container element's border color as well.

**Comment by chjj** [comment]
Strange. Will investigate.

**Comment by chevex** [comment]
Hmmm, I can't seem to reproduce my issue with the border overriding other elements. I tried to narrow it down to a simple demo of the bug and the issue vanish. It has to be something in my app. However, I can reproduce the `style.border` `fg` and `bg` settings not having any effect at all.

**Comment by chevex** [comment]
I figured out the issue with the border stuff. I was using a single `STYLE` object and copying it via [extend](https://www.npmjs.com/package/extend) for each usage of `style` in my controls. I didn't realize that it wasn't telling it to do a deep copy.

Since border styles don't appear to work I was passing `STYLE.border.fg` to `border.fg` etc. Obviously you must set `style.border.fg` and `style.border.bg` behind the scenes when the deprecated `border.fg` and `border.bg` are used. When your code set that on my poorly copied `STYLE` object, it modified the original object graph rather than a copy, changing it for all my controls.

I apologize for the error.
