### ISSUE TITLE
*-fg tags in first item of list widget not honored

### ISSUE THREAD

**Issue by robertklep** [chjj/blessed#111]
Example code (`blessed@0.0.51`):
```
var blessed = require('blessed');
var screen  = blessed.screen();
var box     = blessed.box();
screen.append(box);

blessed.list({
  parent : box,
  tags   : true,
  items  : [
    '1. {red-fg}item #1{/}',
    '2. {red-fg}item #2{/}',
  ]
});

screen.render();
```

The `item #1` text is being shown in the default terminal color, not red, as expected:

![image](https://cloud.githubusercontent.com/assets/1190916/6801309/bab2ae78-d226-11e4-9001-87e529bc85f1.png)

This happens on OS X 10.10, both in iTerm and the default Terminal application. FWIW, *-bg tags work okay.

**Comment by chjj** [comment]
@robetklep, the first item is selected, which is why it is inverted. Blessed does that by default. If you want a non-interactive list, set `interactive: false`.

**Comment by robertklep** [comment]
@chjj crap, I could have sworn that in my larger app I _was_ using `interactive : false`, but it turns out I wasn't. Sorry for the inconvenience!

**Comment by theHazzard** [comment]
I need my list to be clickable, to have the interactive property in true.
Is there any way to prioritize tags in the content? or disable fg on selected items?

**Comment by theHazzard** [comment]
![image](https://user-images.githubusercontent.com/1127332/33578019-d39d9054-d923-11e7-9d72-7c0f8ec477ed.png)

flight-merger-7 is selected, so the small red dot at the beginning of the string must be red, but it is green because the attribute fg of the selected item overwrites the color, even leaving the attribute fg empty.

**Comment by theHazzard** [comment]
@chjj
