### ISSUE TITLE
Enable autoPadding by default.

### ISSUE THREAD

**Issue by chjj** [chjj/blessed#114]
Blessed really should have used autoPadding from the beginning. non-autoPadding apps have issues,  primarily with bordered elements containing shrunken elements. It's impossible to stop a shrunken element within a shrunken element to avoid overlapping the right border. autoPadding fixes all of this by automatically taking into account borders and padding during positioning.

There's a problem though: if we change this, it will potentially break the rendering of any applications that use borders or padding. Developers who upgrade to a newer blessed will have to spend of few minutes changing some positions around or just explicitly autoPadding to false. I'm sort of alright with this. I might do a major release: Blessed 0.1.0, with a list of all major changes developers need to account for.

I'm still not sure on this one though. This is a much tougher change than the rleft->left change.

@secrettriangle, @yaronn, what do you guys think?

**Comment by yaronn** [comment]
Not sure I understand the implication. In general I am very pro breaking api changes if they contribute to the general cohesion of the api / implementation. I will be happy to accommodate blessed-contrib once this is introduced (as a major release like you said).

**Comment by chjj** [comment]
Yaronn, I'll try to explain it. In the olden days of blessed when you had two nested boxes like this:

``` js
var box1 = blessed.box({ parent: screen, left: 0, top: 0, border: 'line', ... });
var box2 = blessed.box({ parent: box1, left: 0, top: 0, border: 'line', ... });
```

`box2`'s border would end up on top of `box1`'s border. In order to get `box2` inside `box1`, you would have to set `left` and `top` to at least `1`.

With `autoPadding: true`, this is automatically calculated for you. If `left` and `top` are `0`, blessed automatically adjusts for the border, placing `box2` completely inside `box1`.

Assuming the same exact box options, this would be the difference:

`left: 0, top: 0` with `autoPadding: false`:

```
+-------+-----+
| box2  |     |
+-------+     |
|             |
|        box1 |
+-------------+
```

`left: 0, top: 0` with `autoPadding: true`:

```
+-------------+
|+-------+    |
|| box2  |    |
|+-------+    |
|        box1 |
+-------------+
```

`autoPadding: false` also has other shortcomings, primarily regarding nested shrunken elements.

**Comment by yaronn** [comment]
autoPadding sounds right. this is not expected to break blessed-contrib as all elements are childs of screen.

**Comment by secrettriangle** [comment]
Sounds good :+1:
