### ISSUE TITLE
xterm not displaying correctly without fake resize

### ISSUE THREAD

**Issue by mscdex** [chjj/blessed#116]
I just noticed that at least with xterm, I've found that some things do not properly render unless the output stream (and thus the Program instance) emits a `resize` event.

For example, I have a Log widget where the first line I write contains white text on a blue background. When viewing the widget in xterm, the blue background shows up but not the text. Other text that I add afterwards, such as plain white text or bolded text show up just fine.

However once I forcefully `screen.program.emit('resize');` the white text shows up on the blue background.

FWIW [Here](https://github.com/mscdex/ssh2/blob/master/examples/server-chat.js) is the script I'm using.

**Comment by chjj** [comment]
``` js
        // disable local echo
        screen.program.attr('invisible', true);
```

You're writing the invisible CSI sequence to stdout before blessed writes the content in your Log. Naturally, the first line of text will be invisible until you hit a `{/}`.

**Comment by mscdex** [comment]
Hrmm, I thought that was to disable local echoing to the screen, not to disable writing of any text. What would be the proper way to disable local echo then?

**Comment by chjj** [comment]
The _attr('invisible') is the invisible SGR attribute CSI code. It just makes text invisible. I'm pretty sure terminal echo can only be disabled with tcsetattr(3), but technically speaking, raw mode doesn't echo. It's equivalent to calling tcsetattr with a big termios bitmask that disables echo. The characters you see on the screen are output by blessed. Some programs like shells don't necessarily do a full raw mode, they still enable echo (like bash), but blessed uses the node raw mode which is more traditional and doesn't echo:

You can see this with:

``` js
process.stdin.on('data', function() {
  ;
});
process.stdin.setRawMode(true);
process.stdin.resume();
```

vs.

``` js
process.stdin.on('data', function() {
  ;
});
process.stdin.resume();
```

What are you trying to do there? There might be a better way to do it.

**Comment by chjj** [comment]
@mscdex, if you want to hide the text in a textbox, you can do `textbox.secret = true;`, and then unset it  once you're done.
