### ISSUE TITLE
Support 100% width blessed.listtable

### ISSUE THREAD

**Issue by jordanarseno** [chjj/blessed#117]
Any chance of supporting 100% width ListTables inside Boxes?

    var blessed = require('blessed');

    var screen = blessed.screen({
      autoPadding: false
    });

    var box = blessed.box({
      parent: screen,
      left: 0,
      top: 0,
      width: '50%',
      height: '100%',
      border: 'line'
    });

    var table = blessed.listtable({
      parent: box,
      width: "100%",
      data: [
        [ 'Animals',  'Foods',  'Times'  ],
        [ 'Elephant', 'Apple',  '1:00am' ],
        [ 'Bird',     'Orange', '2:15pm' ],
        [ 'T-Rex',    'Taco',   '8:45am' ],
        [ 'Mouse',    'Cheese', '9:05am' ]
      ],
      border: 'line'
    });

    screen.key('q', function() {
      return process.exit(0);
    });

    screen.render();

Yields:

![image](https://cloud.githubusercontent.com/assets/757192/6960570/ad4d6076-d8d8-11e4-888b-023200701f4d.png)

Thanks!

**Comment by chjj** [comment]
Yeah, it's a bit tricky right now. Since table width is determined by content, the width option doesn't do much. This is on the todo list though. It should get in before the next release.

**Comment by chjj** [comment]
Should be okay now.

**Comment by jordanarseno** [comment]
Thanks dude!

**Comment by chjj** [comment]
Last implementation was buggy. Should work better now.
