### ISSUE TITLE
Automatic border "docking"

### ISSUE THREAD

**Issue by chjj** [chjj/blessed#118]
In blessed, we all know that overlapping two elements at the border creates something like this:

```
┌─────────┌─────────┐
│ box1    │ box2    │
└─────────└─────────┘
```

Not very pretty, and most people are used to borders that are more cohesive in terminal programs.

Border docking will automatically produce this when borders overlap:

```
┌─────────┬─────────┐
│ box1    │ box2    │
└─────────┴─────────┘
```

I'm still wondering whether this should be default or not, but I'll probably put it behind an option at first.

**Comment by piranna** [comment]
:+1: This is somewhat related what I requested at https://github.com/yaronn/blessed-contrib/issues/30 (or could benefict of) :-)

**Comment by chjj** [comment]
Selective borders (`border: { left: false }`) and border "docking" have both been implemented now. I managed to implement it in a more efficient way than I thought possible. Now, overlapping borders, as long as they are the same color, will automatically "merge". See https://github.com/chjj/blessed/blob/master/test/widget-dock.js for an example. I would have it apply to all borders, but it looked funky if two borders were different colors.

To get borders to overlap on a percentage you can use percentage expressions. e.g. the left box would be `left: 0, width: '50%',` and the right box would be `left: '50%-1', width: '50%+1'`.
