### ISSUE TITLE
How do you make inputs work?

### ISSUE THREAD

**Issue by mrchimp** [chjj/blessed#122]
Apologies if this is just me being stupid and/or this isn't the place to ask but I can't find a way to allow text input. I can't get the following simple example to work. The input is displayed and can be focused but doesn't get any input when typing - U don't think it's just a display issue, getContent() returns an empty string. Am I missing something? There's not a huge amount in the docs about this - it seems like it should "just work". I'm running Xubuntu if that changes anything...

	var blessed = require('blessed');

	var screen = blessed.screen({
		autoPadding: true,
		smartCSR: true
	});

	var form = blessed.form({
		parent: screen,
		name: 'form',
		top: 0,
		left: 0,
		width: '100%',
		height: '100%',
	});

	var input = blessed.input({
		parent: form,
		name: 'input',
		input: true,
		keys: true,
		top: 0,
		left: 0,
		height: 1,
		width: '100%',
		style: {
			fg: 'white',
			bg: 'black',
			focus: {
				bg: 'red',
				fg: 'white'
			}
		}
	});
        
	input.focus();

	screen.key(['escape', 'q', 'C-c'], function(ch, key) {
	  return process.exit(0);
	});

	screen.render();

Thanks for the library - other than this it's been nice and easy to use!

**Comment by chjj** [comment]
You can either call `input.readInput()` or set the option: `inputOnFocus: true`. You can also set `vi: true` and press `i` to enter insert mode once focused.

**Comment by chjj** [comment]
Oh, I didn't realize you were calling `blessed.input()`. blessed.input is an abstract class. You most likely want to call `blessed.textarea()` or `blessed.textbox()`.

**Comment by mrchimp** [comment]
Aha! Using `textbox` instead of `input` and setting inputOnFocus did the trick.

Thanks for the quick reply! Much appreciated!
