### ISSUE TITLE
Override or compose Selected style for list items

### ISSUE THREAD

**Issue by jmatsushita** [chjj/blessed#124]
Hi there,

I would like to display a list item with its tags style when it is selected. I guess there would be 2 ways to make this work:
 1. Simply override the style, when tags is true and there is a style defined for a list item, then the selected style would be ignored. This could be an option (override_selected: true).
 2. Compose styles with a selected style wins approach. In that case when the selected style would have for instance bold: true, then if the list items tags only touch colors then selected items would have a bold style and the colors of the items' tags. If the selected style defines colors, then they would override the item's tags.

My use case is to display an error in red on the selected item after the user has pressed enter and waited for the result. Currently the selected style wins, so I can't display the error in red (which is revealed only when the user navigates away from the current item).

![image](https://cloud.githubusercontent.com/assets/356097/7180006/abefc686-e43d-11e4-8ac5-9b87b00bff67.png)

![image](https://cloud.githubusercontent.com/assets/356097/7180012/b7884de2-e43d-11e4-9ae0-a1f5e5e04ff5.png)

**Comment by chjj** [comment]
This is just a behavior of blessed I thought was easiest. It's hardcoded deep in element rendering that a selected item always has an inverted foreground (or selected style fg) regardless of tags. I like your idea of an override option. We can do that.

**Comment by chjj** [comment]
Also, are you using a regular list there? I highly recommend using the new ListTable element. You can disable the internal cell borders if you want.
