### ISSUE TITLE
error running ansi-viewer

### ISSUE THREAD

**Issue by yaronn** [chjj/blessed#127]
when I run ansi-viewer I get an error:

    Error: Cannot find module 'term.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Terminal.bootstrap (/home/yaronn01/work/blessed/lib/widget.js:8003:15)
        at new Terminal (/home/yaronn01/work/blessed/lib/widget.js:7962:8)
        at Function.Terminal (/home/yaronn01/work/blessed/lib/widget.js:7942:12)
        at Object.<anonymous> (/home/yaronn01/work/blessed/example/ansi-viewer/index.js:32:19)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)

**Comment by chjj** [comment]
You need to install term.js. It's included in the package.json deps. The Terminal element needs term.js for the headless terminal, and pty.js if you don't give a handler (ansi-viewer does).

**Comment by yaronn** [comment]
term.js is used directly by blessed (widget.js) and not by ansi-viewr so term.js should be a dependency of blessed. Currenly npm install will not work - need to manually install term.js.

**Comment by chjj** [comment]
term.js will never be a dependency of blessed. The only thing I would consider is removing the Terminal element altogether since it has a fairly specific purpose and blessed provides more general elements.

**Comment by chjj** [comment]
`cd`'ing to `example/ansi-viewer` and running `npm install` works for me.

**Comment by yaronn** [comment]
did you do it on a clean clone?

I cloned blessed, cd into ansi-viewer and did npm install. then node index
will fail. what am I missing?


On Sun, Apr 19, 2015 at 8:14 PM, Christopher Jeffrey (JJ) <
notifications@github.com> wrote:

> cd'ing to example/ansi-viewer and running npm install works for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chjj/blessed/issues/127#issuecomment-94297780>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by chjj** [comment]
Ah, you're right. I was doing `require('../../')` instead of `require('blessed')`, so the upper level blessed had no idea where term.js was.

**Comment by yaronn** [comment]
great, that works.

btw do I see this art correctly or am I missing some font? lots of question marks.

![image](https://cloud.githubusercontent.com/assets/1359037/7221214/025eb338-e6eb-11e4-8444-574c168495d9.png)

**Comment by jquast** [comment]
I think the artfile you are viewing is encoded cp437, whereas your terminal is utf-8.

Try converting the encoding of the file to utf-8, python3:
```
>>> import codecs
>>> codecs.open('output.ans', 'w', 'utf8').write(codecs.open('input.ans', 'r', 'cp437').read())
```

**Comment by chjj** [comment]
@yaronn, some won't display properly because of either the encoding like @jquast said, or because the art was expected to use working BBS MCI codes which would probably take a while to replicate.

**Comment by yaronn** [comment]
thanks @jquast and @chjj, changing the encoding made it much better!

![image](https://cloud.githubusercontent.com/assets/1359037/7228951/fab554d0-e766-11e4-9af1-4dc73ead507b.png)

**Comment by chjj** [comment]
Yeah, that looks much better. We should try to add an IBM-nonsense decoder to ansi-viewer.

**Comment by chjj** [comment]
Add an ibm-to-utf8 converter via node-singlebyte. Should be better now.

**Comment by yaronn** [comment]
works great!

**Comment by chjj** [comment]
@yaronn,

I kind of want to nerd out on this now.

A lot of these BBS screens are revolutionary. You don't see terminal UI's/art like this anymore, but some of them...

Look at the borders around bbs/hell for example. Or the gradient border on bbs/helpsal. The double borders on bbs/friday13. The artwork on bbs/fl-ill1 and bbs/header.

Blessed should start making some of these possible. At least the double borders and other kind of block backgrounds and borders.

It's almost like terminal graphics have taken a step backwards since the late 80s and early 90s.

**Comment by jquast** [comment]
Just use a different font, OSX Clients should chose an Andale Mono font. Linux fonts should chose an Deja Vu Sans Mono font.

I run a bbs on telnet://1984.ws that is utf-8 compatible, this is the recommendation I give there.

A friend of mine similarly has one on telnet://htc.zapto.org that is also utf-8 compatible.  All other bbs's require a special terminal emulator such as SyncTerm as they don't have any concept of encoding or utf-8: only 8-bit bytes and pairing codepages.

**Comment by yaronn** [comment]
@chjj

couldn't agree more. some of these screens are a few levels above most things you see today. I would love to see the double borders in blessed. 
I think the focus should be on how make people build and use more terminal UIs. One way is with smooth interfaces and UI candy's and this art is great for that. Behind that I think the barrier for adoption is when users need to interact with terminal UIs after being used to the web (or even CLIs in the other end). But the geek in me just want to see all that visual in blessed...
