### ISSUE TITLE
Why inputOnFocus block event loop

### ISSUE THREAD

**Issue by Santinell** [chjj/blessed#131]
until I write a text nothing happens.
messages adds only after keypress

var text = blessed.textbox({
  parent: screen,
  mouse: true,
  keys: true,
  inputOnFocus: true,
  style: {
    bg: 'blue'
  },
  width: '100%',
  height: 1,
  name: 'text'
});

var logger = blessed.list({
  parent: screen,
  top: 2,
  height: '90%',
  width: '100%',
  scrollable: true,
  alwaysScroll: true,
  border: {
    type: 'line'
  },
  style: {
    border: {
      fg: '#f0f0f0'
    }
  }
});

var timer = setInterval(function() {
  logger.add((new Date()).toString());
}, 1000);

**Comment by chjj** [comment]
Hmm, there might be some kind of infinite (or semi-infinite) loop going on here. I'll check it out.

**Comment by chjj** [comment]
I can't reproduce this, but I'm not using a logger to test the setInterval iterations. Maybe it's a problem with the logger.

**Comment by chjj** [comment]
Still cannot reproduce this with a logger.

**Comment by chjj** [comment]
@Santinell, your code is not rendering after the logger.add. This code works fine for me:

``` js
var blessed = require('blessed')
  , screen = blessed.screen();

var text = blessed.textbox({
  parent: screen,
  mouse: true,
  keys: true,
  inputOnFocus: true,
  style: {
    bg: 'blue'
  },
  width: '100%',
  height: 1,
  name: 'text'
});

var logger = blessed.list({
  parent: screen,
  top: 2,
  height: '90%',
  width: '100%',
  scrollable: true,
  alwaysScroll: true,
  border: {
    type: 'line'
  },
  style: {
  border: {
    fg: '#f0f0f0'
  }
  }
});

var timer = setInterval(function() {
  logger.add((new Date()).toString());
  screen.render();
}, 1000);

screen.key('i', function() {
  text.focus();
});

screen.key('q', function() {
  process.exit(0);
});

screen.render();
```

**Comment by Santinell** [comment]
Tested on node 0.12.2 and io.js 1.8.1
Full listing of code:

```javascript

var blessed = require('blessed');

// Create a screen object.
var screen = blessed.screen({
  autoPadding: true,
  smartCSR: true
});

// Quit on Escape, q, or Control-C.
screen.key(['escape', 'q', 'C-c'], function(ch, key) {
  return process.exit(0);
});

screen.title = 'Test';

var text = blessed.textbox({
  parent: screen,
  mouse: true,
  keys: true,
  inputOnFocus: true,
  style: {
    bg: 'blue'
  },
  width: '100%',
  height: 1,
  name: 'text'
});

var logger = blessed.list({
  parent: screen,
  top: 2,
  height: '90%',
  width: '100%',
  scrollable: true,
  alwaysScroll: true,
  border: {
    type: 'line'
  },
  style: {
    border: {
      fg: '#f0f0f0'
    }
  }
});

var timer = setInterval(function() {
  logger.add((new Date()).toString());
}, 1000);

text.key(['enter'], function() {
  var text = this.getValue();
  logger.add(text);
  this.clearValue();
  screen.render();
  this.focus();
});

text.focus();
screen.render();

```

**Comment by chjj** [comment]
Also, you might want to try the Log element instead of using a List.

**Comment by chjj** [comment]
Again, you're not rendering the screen in the setInterval. Try that.

**Comment by Santinell** [comment]
Oh, thanks!! I didn't know about screen.render() with timers.

**Comment by chjj** [comment]
You didn't have to delete your post. It's a simple mistake. I've made it myself from time to time. :)
