### ISSUE TITLE
style.blink (not cursor blink) isn't working

### ISSUE THREAD

**Issue by secrettriangle** [chjj/blessed#132]
```js
var blessed = require('blessed');

var screen = blessed.screen({
  autoPadding: true,
  smartCSR: true
});

screen.key(['escape', 'q', 'C-c'], function(ch, key) {
  return process.exit(0);
});

var box = blessed.box({
  top: 'center',
  left: 'center',
  width: '50%',
  height: '50%',
  content: 'Hello {blink}world{/blink}!',
  tags: true,
  blink: true,
  style: {bg: 'red', fg: 'green', blink: true}
});

screen.append(box);

box.focus();
screen.render();
```

**Comment by chjj** [comment]
Works for me. Check your terminal configuration. Some terminals disable blink by default and have it just highlight cells instead.

**Comment by chjj** [comment]
To enable blink on XTerm: `XTerm.showBlinkAsBold: false`.

To enable blink on URxvt, it must be compiled in.

For iTerm2: I think you change a profile setting or something.

**Comment by secrettriangle** [comment]
Confirmed, thanks. :)

**Comment by chjj** [comment]
This makes me wonder if it's worth creating an "artificial blink" attribute to make up for this shortcoming of terminal configuration.

**Comment by secrettriangle** [comment]
See [here](https://github.com/slap-editor/slap/blob/b64bfa1d636e98cce6e6937e34287907a5aab11c/lib/ui/Header.js#L66-L75) for one possible implementation, if you do decide to go that route.
