### ISSUE TITLE
How do I send a terminal command to a box?

### ISSUE THREAD

**Issue by damionbroadaway** [chjj/blessed#144]
First, sorry. I know this isn't an actual issue.

How do I have a box show the output of a regular terminal command?

For example, say I start with a box that reads "Press 1 to view files." When you press 1 the box shows the output of "ls". Does it need to be a terminal instead? I'm not looking for it to be interactive but if I have to that's fine. 

Thank you.

**Comment by chjj** [comment]
It depends on what you're doing. Grabbing the output of:

``` js
var output = ps.execSync('ls -lah --color=always', { encoding: 'utf8' });
box.setContent(output);
screen.render();
```

Should work fine.

The Terminal element is only there if you're running an advanced terminal program like vim or mutt or something (something that moves the cursor around and changes the screenbuffer).
