### ISSUE TITLE
The PNG/ANSI-Image widget (and naming)

### ISSUE THREAD

**Issue by chjj** [chjj/blessed#147]
For a while now I've been working on-and-off on a [PNG reader](https://github.com/chjj/blessed/blob/master/vendor/tng.js) that would render efficient cellmaps (bitmaps scaled and converted to blessed cells). After I managed to get it passing the de facto PNG test suite, I put it on hold for a while. In the end, it was worthwhile since it seems to be the only javascript PNG reader which supports Adam7 deinterlacing along with bit depths up to 32 (no 48 or 64 yet due to the unavailability of >32 bit bitwise ops in node). It's really surprising how many png readers only support 1-8 bit PNGs.

As added bonuses, it supports animation (APNGs), and it can add various "density" ASCII characters for added detail (based on libcaca/libcucul code).

It sits in its own repo, dubbed "tng", but is vendored in blessed since I don't want blessed to have dependencies (and I originally just wanted it to be a part of blessed): https://github.com/chjj/tng

So, with all that in mind, I decided to whip up a PNG widget for blessed just now. It works well, but I'm unsatisfied with the name. It's just called `blessed.PNG` for now. I was thinking `blessed.Graphic`, `blessed.ANSI[Image]`, or maybe making it part of `blessed.Image` called with an `ansi` option.

Aside: GIFs are also supported, also with animation (the [GIF implementation](https://github.com/chjj/blessed/blob/master/vendor/tng.js#L1207) was much easier to write than the PNG one). Any other image format is supported as long as the user has imagemagick installed. I don't really care about jpegs, so I never wrote an implementation. Plus, they look really complex.

Thoughts?

cc @dbkaplun @mscdex @yaronn

@yaronn, blessed's png reader should be especially useful for blessed-contrib since it looks like `png.js` (used by picture-tube) does not support deinterlacing (or >8 bit depths?).  It also renders straight to SGR content which is inefficient for blessed and will also cause trouble if the image is passing off the screen (say you wanted a logo to slide from right to left off the screen). The blessed PNG reader can render directly to cells, which also allows for efficient animation.

**Comment by chjj** [comment]
See: https://github.com/chjj/blessed/commit/2842f3f6ce406406d830ad3e2fc97ca04daf4f14

**Comment by chjj** [comment]
Also try `$ node test/widget-png.js` for an animating draggable spinning translucent fox that flies around the screen.

**Comment by dbkaplun** [comment]
Is that image transparency I see? Awesome!

Only thing I can think of: maybe call it `image` instead of `png`? Maybe one day someone will write a `webm` reader for blessed, that would be something, huh?

As a side note, one thing I actually don't like about blessed is that it's fairly monolithic. blessed is a Node-only library so dependency fetching isn't as big of a deal as it is browser-side. Would be cool if `program.js` or `tput.js` were separated out into their own modules as well.

Great work!

**Comment by chjj** [comment]
Yep, [_real_ transparency][0] for each pixel's alpha channel using blessed's [color blending algorithm][1]. Well, I say real but I mean semi-real: obviously two characters overlapping can't composite with each other in a terminal, just bg colors. I suppose you could try something wacky for that. If an I and a - overlap you could make a +. That's just the best you can get in a terminal.

This is another reason I hope @yaronn will be pleased with this: rendering straight to ANSI/SGR cannot create transparency like this.

Anyway, `blessed.Image` is already taken - it renders images in the terminal with w3mimgdisplay by overlaying them on the terminal. That way you're not confined to just terminal cells. You get pixels.

I've been thinking for a while about moving `tput.js` into a separate module. I've reserved `tput` in npm (it just requires blessed and only requires npm). However, ncurses is not just a terminfo compiler. It does give you other functions, such as easier ways of dealing with CSR. If blessed is monolithic, it's probably due to tput _and_ all the widgets.

As for the widgets: if you compare it to urwid or curses::ui, it's not that strange. Urwid has at least five very complex elements that blessed does not: BarGraph, HTML generation for using an urwid app in the browser (complete with a server), output for LCD's, Canvas, and BigText (which would be a ton of code to implement each glyph: look at time.js for example. It would probably take more code than a png+gif reader). Urwid also has Terminals and hex colors, like blesssed. Curses:UI has a notebook, a calendar, and a "multi-line" text editor, much more advanced than blessed's primitive one (and I'm sure you know just how primitive it is).

Given all this, I feel like blessed is behind in _some_ areas.

It's a bit weird to have tng.js in the repo, as far as being monolithic goes. I'll consider just making it a dependency in the future.

**Comment by yaronn** [comment]
Hi @chjj 

I was offline for a while and now catching up with everything. I am using a Chromebook at least for the next few weeks and rely on the [secure-shell](https://chrome.google.com/webstore/detail/secure-shell/pnhechapfaindjhompbnflcldabbghjo?hl=en) app (not using developer mode). Generally blessed (and contrib) work though some of the rendering is distorted, sometimes seriously. However the png sample does not render anything at all. I reduced it to the following minimal example which still does not render anything (except a border) even though I'm inside the test folder and I verified the image exists. Maybe related to image-magik dependency?

    var blessed = require('../');
    var fs = require('fs');

    var screen = blessed.screen({
      tput: true,
      smartCSR: true
    });

    var png = blessed.png({
      parent: screen,
      border: 'line',
      width: 50,
      height: 50,
      top: 2,
      left: 0,
      file: './test-image.png',
      scale: 1
    });

    screen.render();

    screen.key('q', function() {
      process.exit(0);
    });

As a side note the [FireSSH](https://chrome.google.com/webstore/detail/firessh/mcognlamjmofcihollilalojnckfiajm?hl=en) app (which I is pure js) does not show distortion for blessed (contrib) but still does not render any png.

**Comment by chjj** [comment]
@yaronn, file is relative to the cwd. So try an absolute path if that file is in the test/ directory:

``` js
var blessed = require('../');
var fs = require('fs');

var screen = blessed.screen({
  tput: true,
  smartCSR: true
});

var png = blessed.png({
  parent: screen,
  border: 'line',
  width: 50,
  height: 50,
  top: 2,
  left: 0,
  file: __dirname + '/test-image.png',
  scale: 1
});

screen.render();

screen.key('q', function() {
  process.exit(0);
});
```

Or just pass an path to `argv` and set file to `process.argv[2]`.

**Comment by yaronn** [comment]
ok, problem was I used node 0.10.37 which does not support zlib sync
methods.

On Sat, Jul 4, 2015 at 4:02 PM, Christopher Jeffrey (JJ) <
notifications@github.com> wrote:

> @yaronn <https://github.com/yaronn>, file is relative to the cwd. So try
> an absolute path if that file is in the test/ directory:
>
> var blessed = require('../');var fs = require('fs');
> var screen = blessed.screen({
>   tput: true,
>   smartCSR: true
> });
> var png = blessed.png({
>   parent: screen,
>   border: 'line',
>   width: 50,
>   height: 50,
>   top: 2,
>   left: 0,
>   file: __dirname + '/test-image.png',
>   scale: 1
> });
> screen.render();
> screen.key('q', function() {
>   process.exit(0);
> });
>
> Or just pass an path to argv and set file to process.argv[2].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chjj/blessed/issues/147#issuecomment-118511351>.
>



-- 

I'm on Twitter (@YaronNaveh <http://twitter.com/#!/YaronNaveh>)

**Comment by chjj** [comment]
Hmm, I suppose we could fall back to async if necessary.

**Comment by yaronn** [comment]
This works great, I've added a reference to it from the picture-tube documentation in the readme as a better alternative.

How do you show colors behind [these 8x2](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors)?

**Comment by chjj** [comment]
@yaronn, I don't understand your question entirely. Are you talking about the transparency? Blessed does the best with what it has. If 256color isn't available it tries to downgrade the colors to what is available. It might not look so great, but that's just a limitation of the terminal.

Anyway, to everyone involved (cc @yaronn @dbkaplun): I've made the `Image` element accept an option called, `itype`, which can either be `ansi` or `overlay`. It's `ansi` by default. `ansi` uses TNG to convert the PNG/GIF into blessed formatted lines using `tng`, and `overlay` uses `w3mimgdisplay` to overlay the full resolution image on the terminal. So now only the `Image` element is necessary.
