### ISSUE TITLE
Issues with resize, focus and blur event.

### ISSUE THREAD

**Issue by nicholasc** [chjj/blessed#149]
So since these are basic events, I am thinking this is more a question than an issue but I can't find enough resources online to help me figure this out. I'm on a Mac using Yosemite and iTerm. I can't seem to be able catch the terminal window's resize, focus or blur events. The keyboard press works fine. Am I missing something?

Here is the code:
```
var blessed = require('blessed');

var Willem = function() {
    var self = this;

    this._screen = blessed.screen({
        smartCSR: true,
        debug: true
    });

    this._screen.title = "Willem";

    this._screen.key(['q'], function (ch, key) {
        return process.exit(0);
    });

    ['resize', 'keypress', 'focus', 'blur'].forEach(function(event) {
        self._screen.on(event, function(){ self._screen.log(1, '[SCREEN]: '+event); });
    });

    this._screen.render();
}();
```

**Comment by chjj** [comment]
Hmm, I just realized you're right about the `focus/resize` events. It's sort of awkward to enable them from Screen:

``` js
self._screen.program._currentMouse.sendFocus = true;
self._screen.program.enableMouse(program._currentMouse);
```

Or

``` js
self._screen.program.write('\x1b[?1004h');
```

I'll add an option for it. NOTE: I'm not sure focus events work with iTerm2, and they definitely don't work if you're using tmux.

As far as `resize` events, I have no idea why you're not getting them. Node handles resize events and sends them to the stream, so blessed can't really fix that if it's not working. This is probably an OS/node issue.

You could try:

``` js
process.on('SIGWINCH', function() {
  self._screen.emit('resize');
});
```

As a workaround.

**Comment by nicholasc** [comment]
Of course, SIGWINCH makes complete sense and works. I haven't tested the new  focus option you added yet. I will later on today and report back.

**Comment by nicholasc** [comment]
All good.
