### ISSUE TITLE
ListTable and oversized content

### ISSUE THREAD

**Issue by TruDan** [chjj/blessed#150]
I have a list table, and the content is too big. It adapts to the content fine, but once the content changes and it's no longer too big, it does wierd things. (The content updates every second)

![image](https://cloud.githubusercontent.com/assets/983207/8505347/21d3a6ee-21db-11e5-98b0-8e42ee83f395.png)

**Comment by chjj** [comment]
Ah, I see. It looks like it's not clearing the previous cells once it gets smaller due to the content, like you said. Fix coming.

**Comment by TruDan** [comment]
Awesome, ty. Will it stay to its fixed size aswell?

**Comment by chjj** [comment]
I can't reproduce this. Could you give me some code to work with?

**Comment by chjj** [comment]
I take it back. I didn't realize you were using a listtable and not table. Fixing.
