### ISSUE TITLE
Blocked event loop

### ISSUE THREAD

**Issue by golbin** [chjj/blessed#151]
I just try to make something for testing blessed.

But I have a problem. I call a function with exec command in blessed UI. But it is hanged during for executing shell command. And if I stroke keyboard several times, then it'll be worked step by step. The code snippets are below. And you can test from https://github.com/golbin/git-commander

```js
Git.prototype.add = function () {
  var deferred = Q.defer();

  process.exec('git add ' + this.getFiles(), function (err, stdout, stderr) {
    if (err) {
      deferred.reject(err);
    } else {
      deferred.resolve(stdout);
    }
  });

  return deferred.promise;
};

//...

screen.key(['C-a'], function () {
  loading.load('excuting...');

  git.add()
    .fail(function (err) {
      // TODO: show alert box
      console.log(err);
    })
    .done(reload);
});
```

**Comment by golbin** [comment]
It works right if I use child_process.execSync instead of child_process.exec.

But I would like to know why. And is there way to fix it even if I use child_process.exec?.

**Comment by chjj** [comment]
Could you give me a standalone gist that replicates this issue?

**Comment by chjj** [comment]
> And if I stroke keyboard several times, then it'll be worked step by step.

This makes me think that you may not be calling `screen.render()` in the `reload()` function when needed. A full gist would be appreciated.

**Comment by golbin** [comment]
I changed my code from async to sync logic so I cannot replicate this. I'll report again when I'll be faced this. Thanks.
