### ISSUE TITLE
ansiimage.js not checked in

### ISSUE THREAD

**Issue by yaronn** [chjj/blessed#153]
I get this message upon require('blessed') from master:

    Error: Cannot find module './widgets/ansiimage'
        at Function.Module._resolveFilename (module.js:336:15)

**Comment by yaronn** [comment]
same for OverlayImage.

**Comment by chjj** [comment]
Wow, I forgot to `git add` them after renaming them. That was embarassing. Thanks for pointing that out. That went unnoticed by me for too long.
