### ISSUE TITLE
Using blessed with nw.js throws error 'Uncaught Error: Not a terminal'

### ISSUE THREAD

**Issue by adatech** [chjj/blessed#162]
I am trying to use blessed with nw.js and it is throwing an error:

```
Uncaught Error: Not a terminal.
```

It seems the error might be coming from the fact that process.stdout.WriteStream doesn't exists. With nw.js there is only process.stdout.SyncWriteStrem. Is there a way to make that work for Blessed output?

**Comment by chjj** [comment]
Old versions of blessed check for isTTY and throw if output is not a tty. Please update blessed.

**Comment by adatech** [comment]
Updating to the latest seemed to fix the problem. Thank you.
