### ISSUE TITLE
Why did the npm version dip?

### ISSUE THREAD

**Issue by anko** [chjj/blessed#165]
[`v0.1.61`](https://github.com/chjj/blessed/commit/ebdd1940fe403daf0300b5faa4baacb011df9dbd) existed, then it was mysteriously decreased to [`v0.1.7`](https://github.com/chjj/blessed/commit/cc7c9cbe033be5f81568599b2da17a01f27eabc7) and has since increased to the current [`v0.1.21`](https://github.com/chjj/blessed/commit/364a56f4dc3bf8d5434e99bc0773062fbeca05bc).

Why was that done?

It causes really confusing `npm update` behaviour:

```
$ npm install --save blessed
blessed@0.1.21 node_modules/blessed
$ npm update
blessed@0.1.61 node_modules/blessed
```

- - -

For a log of versions on npm and when they were published:

    npm view --json blessed | jq '.time'

**Comment by chjj** [comment]
Yikes, that v0.1.61 is supposed to be 0.1.6-1. I could remove v0.1.61 from npm but that might break existing projects. It looks like we're in for an early bump to v0.2.0 because of this.

**Comment by chjj** [comment]
So, changing npm wasn't an option since I don't want any projects that rely on 0.1.21 to break. I've bumped the latest version to v0.1.80. Thanks for bringing this up.

**Comment by anko** [comment]
Sounds good. Thanks for responding so fast again. :sparkles:
