### ISSUE TITLE
Allow textarea to bubble keys up

### ISSUE THREAD

**Issue by arkadiyt** [chjj/blessed#170]
I'd like to implement a textbox that selectively bubbles input up - for instance if my form has a number field I'd like to have the textarea consume all digit characters but bubble up other characters (like escape or control-c) so that people can close the form intuitively.

Currently this is not possible because textarea and textbox both have 'keypress' listeners that do not return anything.

My current implementation performs a monkey-patch to make this work:
```javascript
var oldListener = blessed.textbox.prototype._listener;
blessed.textbox.prototype._listener = function(ch, key) {
  oldListener.call(this, ch, key);
  return true;
};
```

Would it make sense to provide an option to control this behavior?

**Comment by chjj** [comment]
Textarea grabs/locks keypresses when in insert mode. The `Screen` object has an option that allows you to get around this. You could do:

```
screen = blessed.screen({
  ...
  ignoreLocked: ['C-c', 'escape']
});
```

And C-c and escape from the textarea would still be propagated properly. Would that solve your problem?

**Comment by arkadiyt** [comment]
That worked, thanks!
