### ISSUE TITLE
Event emitter hook for every events

### ISSUE THREAD

**Issue by Yomguithereal** [chjj/blessed#171]
Hello @chjj, would you be willing to consider to extend the `blessed` event emitter to accept a listener handling every events? Something of this kind:

```js
node.onAny(function(type, payload) {});
```

**Comment by chjj** [comment]
Yeah, I would consider that. I'd rather make it special event though: `element.on('emit')` or `element.on('event')`. The only thing I worry about is the bubbling. It might be a hit to performance if these events hve to bubble along with the actual event. We'll see. Maybe I'm just being paranoid, or we could just have it not bubble.

**Comment by Yomguithereal** [comment]
Adding an `event` event seems to be a good and simple way to do so even if this feels a bit meta :).

To add some background to this issue [this](https://github.com/Yomguithereal/react-blessed/blob/master/src/ReactBlessedInjection.js#L34-L53) is where I monkey patch the `blessed` emitter to be able to catch events efficiently with `react-blessed`.

**Comment by Yomguithereal** [comment]
Thanks @chjj. Will switch to `0.1.81` asap.
