### ISSUE TITLE
Mouse events not registering past 96th block

### ISSUE THREAD

**Issue by davidmarkclements** [chjj/blessed#20]
I've trimmed this down to a single element in the terminal, that is 20 chars wide, positioned at right:0. 

If I resize my terminal past 116, clicks are no longer recognized on the element.

If I I resize to 115 width, only the first character block of my element registers clicks, 
if I resize to, say, 50 clicks trigger just fine anywhere on the element. 

The terminal is gnome-terminal on Fedora

**Comment by mgliewe** [comment]
seems to be the same issue as #89

**Comment by chjj** [comment]
Closing. Discuss this in #89 like @mgliewe said.
