### ISSUE TITLE
Blessed IRC Channel

### ISSUE THREAD

**Issue by chazu** [chjj/blessed#256]
Apologies if this is not an appropriate venue for this discussion, however I wondered whether anyone would be interested in setting up an IRC channel for blessed - official or unofficial (one # or two) on freenode. I tweeted @chjj about it but I don't believe he's very active on the twitters, so I was hoping for some discussion here.

If not an IRC channel, perhaps a mailing list would be good. Any thoughts? Tagging @yaronn here because I think he'd be interested in the idea.

**Comment by mtwomey** [comment]
+1 there seems to be no acknowledged forum for discussion.

**Comment by chazu** [comment]
@mtwomey  I've created ##blessed on freenode. I'll close this issue.
