### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Coalman** [chjj/blessed#28]
I've been working on a npm module https://github.com/Coalman/blessed-life and I decided to test it on windows. It seems like there are artifacts when I run it and new lines are added to the output sometimes. I was wondering if perhaps windows support is broken or if I didn't do/setup something correctly?

I've tried it in git bash/cmd and some of the examples of artifacts (the ping one). Everything works fine on linux.

**Comment by chjj** [comment]
Most likely fixed with #130.
