### ISSUE TITLE
Web browser - Opposite of a rasterize() supported?

### ISSUE THREAD

**Issue by 7fe** [chjj/blessed#294]
It appears to support basic functionality that a web browser might use.
It could support like HTML4 or something like that.
**EDIT:**  Is the opposite of a rasterize function supported or have any plan to support?

Then we could render images using anything and have the output to terminal.

If you would prefer me to open a new issue(or non at alll) that wouldn't be a problem or if more description is needed.  I believe it would take just basic Optical character recognition.

**Comment by piranna** [comment]
HTML4 would be overkill for blessed itself, but a HTML4 renderer would be implemented on top of it the same way there's a React renderer (and I would love to see something like this :-D)

**Comment by 7fe** [comment]
@piranna please let me know if you have any ideas.  It would be awesome if you could develop applications that are both browser and terminal supported.  If done right you can translate the drag and drop panes in the terminal to equivalent JavaScript apis

**Comment by piranna** [comment]
The first thing would be to clean-up the project architecture to allow double buffering and remove the non-esential widgets. that's the purposse of blessed-ng but I don't have time to work on that. After that, it would be easy to implement the DOM elements on top of the blessed basic widgets, but would need a lot of work... Probably react-blessed is the best option at this moment.

**Comment by 7fe** [comment]
@piranna it sounds like you have more experience with this but do you think it would be possible to maybe spawn a chrome process and simply convert that to a canvas or something terminals support?

**Comment by piranna** [comment]
Yes, it would be possible, but the result will be absolutely useless.

**Comment by pt300** [comment]
@limeblack As far as I'm concerned what you are asking about is no longer related to blessed. And yes, you can use something like phantom.js to render webpages and later use own logic display them as raster graphic in terminal. I have to say that it's a terrible idea and won't really work as good as you would want it to.
