### ISSUE TITLE
List Index is incorrect?

### ISSUE THREAD

**Issue by stefannew** [chjj/blessed#299]
I'm seeing an issue wherein the index of a list item is incorrect - it seems to be off by two.

Here's a screen of the list items:

<img width="543" alt="screen shot 2017-05-09 at 12 25 54 am" src="https://cloud.githubusercontent.com/assets/3951747/25835605/0c6aef88-344e-11e7-87f0-1fc03cb2b986.png">

And here's the code used to render the list:

```
const ContentList = require('./components/content-list');
WindowContainer.append(ContentList);

ContentList.add('one');
ContentList.add('two');
ContentList.add('three');

Screen.render();


```

Where ContentList is an instance of blessed.list:

```
const ContentList = Blessed.list({
  height: '99%',
  keys: true,
  left: 'center',
  scrollable: true,
  style: {
    selected: {
      bg: '#ffffff',
      fg: '#000000',
    },
  },
  tags: true,
  top: 'center',
  width: '99%',
});
```

But the index returned on `select` is incorrect:

<img width="264" alt="screen shot 2017-05-09 at 12 27 24 am" src="https://cloud.githubusercontent.com/assets/3951747/25835622/3fd7d804-344e-11e7-9172-ad9b7180ad25.png">

Am I doing something wrong, or is this an issue?

**Comment by stefannew** [comment]
It seems a more consistent index is returned when I call `getListIndex(item.content)` of the list i'm operating on, which seems insane:

```
ContentList.on('select', item => {
  console.log(ContentList.getItemIndex(item.content));
});
```

**Comment by zach-is-my-name** [comment]
the second callback arg is the index from 0.  There's also a prop on the first callback arg called index which is indexed starting at 1
<details> 

<click here for 2 onSubmit args>

**Comment by zach-is-my-name** [comment]
The callback has a second param that is the zero based index.  The property of the submit object is 1 based for some reason
