### ISSUE TITLE
Can I implement a click event on the listtable header item?

### ISSUE THREAD

**Issue by lanjingling0510** [chjj/blessed#300]

**Comment by pt300** [comment]
Header box is hidden under [_header](https://github.com/chjj/blessed/blob/master/lib/widgets/listtable.js#L54) property of list table. I guess that should help you.

**Comment by lanjingling0510** [comment]
@pt300 Thank you for your answer.I looked at the source, _header is a box, its content is a text, seemingly can not be divided into multiple binding click event boxes.
