### ISSUE TITLE
example mising a background element

### ISSUE THREAD

**Issue by troywweber7** [chjj/blessed#310]
I'm just running the example and the first letter of "Hello, world" is cut off. Background:

```bash
$ node -v
v8.4.0
$ npm -v
5.3.0
$ npm list blessed
/home/troyw/Code/personal/test-board
└── blessed@0.1.81
```

![screenshot from 2017-09-02 21-53-13](https://user-images.githubusercontent.com/4765979/30000689-fbfcf9d8-9029-11e7-99f4-843a6ec206cc.png)

**Comment by diego-c** [comment]
It's related to the image:

```
var icon = blessed.image({
  parent: box,
  top: 0,
  left: 0,
  type: 'overlay',
  width: 'shrink',
  height: 'shrink',
  file: __dirname + '/my-program-icon.png',
  search: false
});
```
If you set the `width` and `height` properties to `0`, it works.

**Comment by troywweber7** [comment]
Thanks!
