### ISSUE TITLE
About the color types

### ISSUE THREAD

**Issue by diego-c** [chjj/blessed#335]
According to the documentation, taking the Border object as an example, it says:

> - __border__ - Border object.
>      - __type__ - Type of border (`line` or `bg`). `bg` by default.
>     - __ch__ - Character to use if `bg` type, default is space.
>      - __bg, fg__ - Border foreground and background, *__must be numbers (-1 for
    default).__*
>      - __bold, underline__ - Border attributes.

And about the colors:

> ##### Colors

> Colors can be the names of any of the 16 basic terminal colors, along with hex
> values (e.g. `#ff0000`) for 256 color terminals. If 256 or 88 colors is not
> supported. Blessed with reduce the color to whatever is available.

I understand that something like:

```
const border = {
    fg: 0,
    bg: 22
}
```
Could be similar to:

```
const border = {
    fg: 'black',
    bg: 'green'
}
```

But shouldn't it say that `fg` and `bg` could also be strings?

**Comment by ghost** [comment]
> Colors can be the **names**...

**Comment by diego-c** [comment]
@hypersad Exactly, so why does the first quote for the Border object says `bg` and `fg` must be numbers?

I'm just curious, because in [@types/blessed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/blessed/index.d.ts#L478) the same quote is referenced and `bg` and `fg` are also defined as numbers.

**Comment by ghost** [comment]
Could it be outdated? Or, maybe there is some kind of internal converter.

**Comment by diego-c** [comment]
Yep, looks like the colors are mapped and converted on [lib/colors.js](https://github.com/chjj/blessed/blob/master/lib/colors.js#L375). Also referenced on #108. 

Thanks for the response. I'll open a PR, though not sure if the project is still actively maintained.
