### ISSUE TITLE
Handling keypress for nested elements

### ISSUE THREAD

**Issue by oliversturm** [chjj/blessed#341]
I'm trying to have a structure like this:

```
screen
  box (root)
    box (view)
      child elements...
```

The idea is that I can then exchange one `view` for another at runtime. This generally works fine.

Now, I'd like to handle keystrokes on the `view` level. View A might react to `F5`, but View B might not - makes sense. However, this doesn't seem to work - I can't figure out how to reliably receive keypress events on the `view` level when the focus might actually be on a child element nested in the `view`.

I've created a test in [this gist](https://gist.github.com/oliversturm/3be0e3b348843f984f95fde060344285). You can see in there that `root` has a handler for the `x` key. If `root` is focused, that handler works correctly. However, if `kid` is focused (which is an element nested inside `root`), then `root` doesn't receive an event for the keypress.

To put it yet another way: I would like my `root` element to receive all the keypress events that `screen` also sees. Pressing `t` in the test scenario is always caught by `screen`, but not by `root`. How do I do that?

You can see that I've also tried using the `element keypress` syntax hinted at in the README. Unfortunately this doesn't behave as expected either - none of my `element keypress` events is received reliably, only the `screen` level one strangely triggers after two `F12` keypresses, but doesn't yield any event information.

**Comment by oliversturm** [comment]
Update: I just found, by reading source code, that the event handler for `keypress` has three parameters. So I was able to receive that `F12` key in the sample, on the second keypress - gist updated. Nothing else changes though!

**Comment by oliversturm** [comment]
Found the problem after lots of tests. It turns out that in my test, both the `root` and the `kid` element must have `keyable: true` - then suddenly everything works as expected.

**Comment by blekmus** [comment]
@oliversturm I know I'm more than 3 years too late, but could you share a gist of your solution.

**Comment by oliversturm** [comment]
@blekmus I have updated [the gist](https://gist.github.com/oliversturm/3be0e3b348843f984f95fde060344285) to the latest version I found in my repo - unfortunately haven't worked on the project in a couple years. The version now in the gist has the two `keyable:true` settings I was referring to above, so I hope it will help you figure it out!

**Comment by blekmus** [comment]
@oliversturm thanks very much for the update. I finally figured it out!


Like you, I'm trying to make a cli with multiple pages (views) under one root. Each mounting and dismounting based on different events. And having access to events down the line is really important. So this helped me out a lot.
