### ISSUE TITLE
Better input for blessed

### ISSUE THREAD

**Issue by antonmedv** [chjj/blessed#369]
Blessed has two widgets for input: textbox and textarea, but they lack lots of functionality. For example you can't navigate on them using C+a/C+e.

I'm looking for some alternative implementation for textbox. Do you know one?

PS I tryed slap's editor-widget, but it's too heavy (using atom's text-buffer)

**Comment by amoblin** [comment]
同问。设置光标的位置的接口何时能开放呢？
