### ISSUE TITLE
Textbox cannot be styled

### ISSUE THREAD

**Issue by Sakuya-Izayoi** [chjj/blessed#388]
I've a simple text box at the bottom of my screen:
```js
const input = blessed.textbox({
  width: '100%',
  left: '0',
  bottom: '3',
  height: '3',
  border: {
    type: 'line'
  },
  style: {
    fg: 'white',
    bg: 'black',
    border: {
      fg: 'white'
    }
  }
});
```
I append it directly to the screen and the `readInput` from it. The cursor appears, I can type text and when I press `Enter` it processes the input. The problem is that my input box is not visible, it has no border and text is black on black (i guess). I use gnome-terminal with xterm color scheme.

**EDIT:** further investigation showed that adding `height` property to textbox breaks it.

**Comment by baishuijianjia** [comment]
Can you tell me specifically how you solved it
