### ISSUE TITLE
TERM=xterm should work the same as TERM=linux

### ISSUE THREAD

**Issue by rngadam** [chjj/blessed#41]
Opening an GNOME Terminal, the variable TERM is set to xterm.

Running a sample app (the list), results in the borders appearing as characters instead of line. If I manually set TERM=linux, the program displays correctly.

Note that alsamixer (as an example) on the other hand behavers correctly whether TERM is set to xterm or linux.

**Comment by straub** [comment]
With `TERM=xterm-256color`, `node ./examples/dashboard.js` is showing characters q, x, etc. instead of the borders. `TERM=linux` breaks everything, makes a mess of the terminal. :smiley: 

Sparklines also show some missing characters, although I'm not certain if that's due to my font or not (Consolas).

My terminal is PuTTY on WIndows 8.1.

**Comment by perfaram** [comment]
@straub : I was about to post an issue about that (I already did - and closed, now - on /yaronn/blessed-contrib). I'm on OSX 10.10, $TERM=xterm-color. I'm *pretty* sure this is not related to blessed - I ran across all the border displaying code, in "widget.js". There, there is no "q", "x", "l", "j", "q"... 
It must be related to node

**Comment by perfaram** [comment]
Okay, so I made some test, and there a logic :
│ = x
┌ = l
┐ = k
─ = q
└ = m
┘ = j

**Comment by chjj** [comment]
v0.0.39 should have fixed this. If not, the TERM is incorrect. TERM=linux sets brokenACS to true in all cases - it ends up using unicode instead of ACS.

**Comment by KaKi87** [comment]
Hello, I'm also experiencing this issue,

> │ = x
> ┌ = l
> ┐ = k
> ─ = q
> └ = m
> ┘ = j

Using Windows 10 :

- on PuTTY, wether `Configuration > Connection > Data > Terminal-type string` is set to `xterm`, `xterm-256color`, `xterm-linux`, `linux` or `cygwin`.
I also changed the font from `Courier New` to `Consolas`, which did _not_ fixed the issue.

- on CMD and PowerShell.

However, everything works fine on `cmder`, while both CMD/PowerShell and cmder have the `TERM` environment variable set at `nutc` and use the `Consolas` font.

Thanks
