### ISSUE TITLE
Doubling of characters on Textbox

### ISSUE THREAD

**Issue by jacoboneill** [chjj/blessed#435]
I am writing a [chat-app](http://www.github.com/jacoboneill/chat-app) where there is a textbox inside a form. When you press enter it clears the textbox, focuses the textbox and then renders the screen, however after the first time pressing enter it will double the inputs. Can't find any solutions online.

Please help!

**Comment by zyriab** [comment]
This lib is not being maintained... last commit was 8 years ago. You might wanna check [Reblessed](https://github.com/kenan238/reblessed)

**Comment by jacoboneill** [comment]
@ZyriabDsgn Thank you 👍
