### ISSUE TITLE
How to set width/height based on character count?

### ISSUE THREAD

**Issue by kenokabe** [chjj/blessed#74]
I understand width/height property can be set as number(px), % etc.

Is it possible to set them based on font charcter/element count?

There is an API 

```
foo.setLine(line_number, txt);
```

In that case, we control the element with line by line, and I wonder if the same can apply to window size and position.

Thanks.

**Comment by chjj** [comment]
Size, yes. Position, no.

`height: 'shrink'` or `width: 'shrink'` will accomplish what you want.
