### ISSUE TITLE
Mouse, Click events not detected?

### ISSUE THREAD

**Issue by MohammedFadin** [chjj/blessed#86]
Hello,

I was playing with Blessed today, but it seems that the mouse and click events are not detected for some reason. I'm using OSX terminal, and lunching the app using node app.js if it matters.

Note: I even copied the snippets from the readme and no success.

Thanks in advance!

**Comment by chjj** [comment]
@MohammedFadin, I played around with Terminal.app today. It does not support mouse events. iTerm2 is probably better, and does support mouse events (however, it does not display ACS correctly). Honestly, I would say your best bet for a terminal on OSX is to run a headless X11 server and open an xterm+tmux or urxvt+xterm.

**Comment by secrettriangle** [comment]
@MohammedFadin FYI you can get mouse support in Terminal.app using SIMBL+MouseTerm, though iTerm2 is decidedly better.
