### ISSUE TITLE
Support iojs

### ISSUE THREAD

**Issue by secrettriangle** [chjj/blessed#92]
If you run `iojs test/widget-form.js`, focus the `Input`, and move the mouse, the input is filled with garbage. Running iTerm2 Build 2.0.0.20141103 with iojs v1.0.2.

Possibly related: #91

**Comment by timoxley** [comment]
@secrettriangle can you confirm this does work using legacy node (0.10.x) or is this specific to io.js?

**Comment by secrettriangle** [comment]
@timoxley this affects `iojs@9b81c3e7` (current `v1.x` branch) and `node@016e0845` (current `v0.12` branch) but not `v0.10.34`.

**Comment by chjj** [comment]
@secrettriangle, this is bizarre. If it thinks the mouse protocol is a keystroke, it still shouldn't output it. Could you try running `test/program-mouse.js` and tell me what happens?

**Comment by secrettriangle** [comment]
It works just fine with `node@v0.10`, but `v0.11.14+` and `iojs` both seem to treat ANSI escape codes for the mouse movement as keystrokes, so they don't shadow my mouse in blue as they should and I see strange keystroke events rather than `mousemove` events as expected. However `mousedown` and `mouseup` seem to work as expected.

**Comment by chjj** [comment]
I see. We might just have to include our own superior version of `readline.emitKeypressEvents` within blessed. node.js has been altered a lot as far as that function goes. This isn't the first time it's caused issues either.

**Comment by chjj** [comment]
It should be okay now. Give it a try.

**Comment by secrettriangle** [comment]
This code is problematic -- if multiple keystrokes come through, it treats it as one long sequence and only handles the first keystroke as opposed to splitting out each keystroke into its own separate `keypress` event. Here's an example: https://gist.github.com/anonymous/0495ef10777e9dd68774

**Comment by chjj** [comment]
It's certainly better than spitting junk in the terminal from a regression. I went and took one of the older readline commits. Feel free to improve it and submit a PR.

**Comment by chjj** [comment]
@secrettriangle, I've added you as a collaborator. Feel free to make commits to keys.js.

**Comment by chjj** [comment]
@secrettriangle, any progress on keys.js? I'd like to get those commits in before a release. I also want to do a release for all of the fixes I recently made, mostly related to box scrolling.

**Comment by secrettriangle** [comment]
Thanks @chjj! :)

I'm really busy these days but I'll try to take a look sometime soon! Don't feel as if you have to wait for me to take a look at `keys.js` to release -- I think we should release early and often.

**Comment by chjj** [comment]
This fix should also remove blessed from the io.js thread (mentioning it here to follow the rules): https://github.com/iojs/io.js/issues/456
