### ISSUE TITLE
Doesn't work on NodeOS

### ISSUE THREAD

**Issue by piranna** [chjj/blessed#98]
On NodeOS terminal (that's in fact a Linux ```/dev/console``` pty) output shows nothing at all, only a blank screen. Seems to be related to https://github.com/chjj/blessed/issues/41, since it seems to be of type ```TERM=linux```.

**Comment by chjj** [comment]
Could you show me an example of some code you're using? This might have something to do with the terminfo parser.

**Comment by piranna** [comment]
I've just tried to run the blessed-contrib demo, but also blessed time
example fails. I have been running NodeOS on QEmu and redirect the text
output to a host terminal (terminator), don't know if it affect... When
finishing the demos, the terminal works correctly.

**Comment by chjj** [comment]
It would be really nice to narrow this down to a small chunk of code (even a single escape code). blessed-contrib uses a lot of different features. time.js, not as much, but there's still a lot of sequences flying around. I would recommend testing a small script that enables ACS or something similar. This might be akin to an issue we ran into with a sun console a while back. Blessed was outputting real unicode characters instead of using the actual ACS, and the sun console wasn't able to handle unicode. As a result, the sun terminal interpreted every byte it could as a sequence, and the screen was rendered blank.

Are your utf-8 locales compiled? What does /etc/locale.conf say if you have one? What is the contents of your $LANG and $LC_COLLATE?

**Comment by piranna** [comment]
Ok, I've just tried to exec it directly and it works, and it's really pretty :-)

Seems the problem is related with the redirect of the characters from the QEmu serial port to the Terminator terminal.

![blessed-contrib](https://cloud.githubusercontent.com/assets/532414/5929444/1e4fc41c-a684-11e4-8554-411d40157f7f.png)


By the way, why are the lines not being correctly drawn? Is it due to the low resolution used by default (80x25) or due to Linux console not having unicode symbols? How could I be able to fix it (NodeOS is minimalistic, by the way...)?

P.D.: I think terminator support UTF-8 characters, but it makes sense what you said about the Sun terminal, because seems it's the same result (a blank screen). The image I've send is an screenshoot of the QEmu window, that's mimicking the emulated framebuffer and that's why they are shown, since they are not transfered but instead directly paint to the (virtual) screen...

**Comment by chjj** [comment]
The lines are an ACS problem. Blessed thinks the terminal has switched to ACS when it hasn't, so you end up getting ascii junk instead of lines. There can be a number or combination of reasons for this.

**Comment by piranna** [comment]
The lines seems I'll need to add some things to NodeOS, but the connection over the virtual serial port should work "as is"...

http://www.linuxfromscratch.org/lfs/view/6.2/chapter07/console.html

**Comment by chjj** [comment]
I may have found the issue with the linux console's ACS. Will push soon.

**Comment by chjj** [comment]
ACS (or lack thereof)*

**Comment by chjj** [comment]
Also, @piranna, the only way I see the linux console using ACS without having it is that you had the wrong $TERM set. If $TERM was not set to linux, it would not fallback to the unicode characters. You said you were running this in qemu's curses interface. That means your terminal is different from the one the kernel is emulating.

**Comment by piranna** [comment]
Here we have two use cases, that's why I've got two diferent results :-)

1. running NodeOS on QEmu on its own window with an emulated screen. This is the usual VM style, and the one that worked with the previous screenshot. I have been reading about Linux unicode support and seems that since NodeOS is just Node.js directly running on top of Linux kernet, ```/dev/console``` is running on ASCII mode, not being capable of showing any character >= 0x80 (so that's why it show normal characters and not strange simbols, since there's no Extended ASCII characters loaded and any byte with its first bit set to 1 is ignored). To enable Unicode support I'll need to add and execute [unicode_start](http://www.tldp.org/HOWTO/Unicode-HOWTO-2.html#ss2.1), I'm not too much into adding more things to NodeOS and also I'm not sure if it would work, but "standard" Linux distros are doing it already and seems it's the only way to go, so this point seems to be my fault :-P
2. running NodeOS on QEmu but redirect the console output to a serial port by using ``` '-append', 'console=ttyS0```. In this case I got a blank screen, so it could be something related to the previous point, the QEmu virtual terminal, or the terminator (gnome-terminal) console.

In any case, $TERM is set to 'linux' by default by the Linux kernel, other thing is, as I've told you, that terminator is doing some nasty things.

**Comment by chjj** [comment]
Terminator is gnome-terminal under the surface if I'm not mistaken. gnome-terminal uses the xterm terminfo, which supports ACS. Older versions of the linux console do not support ACS. There's a dissonance here which would explain why ACS chars come out as regular ASCII. I've just tested the linux console and it works fine with unicode line drawing. Closing this for now, unless something else comes up.

**Comment by piranna** [comment]
> Terminator is gnome-terminal under the surface if I'm not mistaken. gnome-terminal uses the xterm terminfo, which supports ACS.

You are right :-)


> Older versions of the linux console do not support ACS.

I'm using Linux 3.18.3, so this is not a problem.


> There's a dissonance here which would explain why ACS chars come out as regular ASCII. I've just tested the linux console and it works fine with unicode line drawing.

I've just tested on a linux console on my Ubuntu machine and found the
same ASCII chars that the previous image on NodeOS... I've noticed
that the "high definition" dot lines done by using braille glyphs are
shown as blocks (the same as the image), so maybe it's a problem of
not having installed a Unicode font for the terminal? By executing
unicode_stop it shows a lot of ugly acentuated characters like when
seeing a web page with a bad charset, but the border lines are shown
correctly instead of as alphanumeric characters (using ASCII lines?).
I've also tested it by using
http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt with
similar results, hope this helps... :-)


> Closing this for now, unless something else comes up.

Ok, I'm going to try to find a console Unicode font for this :-)


-- 
"Si quieres viajar alrededor del mundo y ser invitado a hablar en un
monton de sitios diferentes, simplemente escribe un sistema operativo
Unix."
– Linus Tordvals, creador del sistema operativo Linux

**Comment by piranna** [comment]
Ok, I've read a little bit more... and seems that the problem on the Linux console is simple a [hardware limitation issue](http://en.wikipedia.org/wiki/VGA-compatible_text_mode#General_restrictions) :-( Linux console (```/dev/console```, ```/dev/tty[0-83]```) is using VGA text mode, that only allow simultaneously 256 glyphs at 16 colors or 512 glyphs at 8 colors, definitely too few to show just a bunch of Unicode characters. By default, Linux console [start using UTF-8 characters with the build-in CP437 charmap font](https://wiki.archlinux.org/index.php/fonts#Console_fonts). This can be changed afterward, but if the console loaded font doesn't support one of the Unicode glyph, it's shown as a block char instead (just like the image above, and the reason why using ```unicode_stop``` it fall-back to use ASCII lines chars), so willing to exec the [blessed-contrib demo](https://github.com/yaronn/blessed-contrib/blob/master/examples/dashboard.js) with all its bells and whistles on a Linux console (the ones shown by pressing Ctrl+Alt+1 to 6) is a lost battle :-(

So here we have several, somewhat unrelated problems:

- [ ] on a Linux console, showing alphabetic characters instead of Unicode lines. When disabling Unicode support it show ASCII lines as a fallback, so it would be just to somehow detect this situation (how?) and render the ASCII lines directly instead of the Unicode lines. Maybe a flag would be enough by the moment :-) Another alternative would be to craft a 512 glyphs font that have the required ones (mostly braille like [ubraille](https://www.archlinux.org/packages/extra/any/ttf-ubraille/) and Unicode lines) and load it instead of the default one...
- [ ] the blank screen when connecting to QEmu using the virtual serial port. Terminator is using UTF-8 by default, I could use another codec to see if it works. I could also redirect the output to a file to see what's being actually send.

**Comment by piranna** [comment]
OMG... the problem with the linux console is a kernel bug!!! O_O

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=763731
that reference the bug
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=515609
that reference the patch
http://lkml.iu.edu/hypermail/linux/kernel/0602.2/0887.html

and seems since 6 years ago it has not been fixed!!! O_O

I was going to suggest you could update [blessed ACS vs. UTF-8 detection](https://github.com/chjj/blessed/blob/master/lib/widget.js#L1082-L1119) since seems Linux console does support UTF-8 but not ACS, but I'm not totally sure if if it's the correct fix or just a workaround now that I know there's some kernel related issues... :-( What do you think?

**Comment by chjj** [comment]
@piranna, that bug is well known. ACS is considered "broken" by ncurses in the linux console. You're supposed to use unicode lines instead. (However, testing it recently, ACS seemed to work for a second, but don't quote me). Blessed also considers ACS "broken" and uses unicode lines instead. If unicode is disabled, blessed tries to draw lines with just ASCII (they don't look pretty). However, what you're getting is a mix of both: the terminal doesn't support ACS but blessed thinks it does. You have conflicting terminfos.

**Comment by piranna** [comment]
> You have conflicting terminfos.

Sort of, more exactly missing ones :-) Since in that bug they made references to ```linux-vt``` and ```linux2.6``` descriptions and I only had ```linux``` one from the ```ncurses-base``` Ubuntu package (why something so "basic" is in a particular library package instead of being independent?) I've searched for the missing ones and found they are at the [ncurses-term](http://packages.ubuntu.com/vivid/all/ncurses-term/filelist) package. Install it, set the $TERM environment variable to ```linux-vt```... and now I the border lines are rendered :-P Maybe you could include a little reference to ```ncurses-term``` in the readme since it's a so obscure issue, isn't it? :-/

Ok, blessed is correctly working, now I need to test it on NodeOS... I hope is only needed to copy the terminfo file... :-P

P.D.: oh, and sorry for the spam... :-P

**Comment by piranna** [comment]
By the way, the Linux Console issue seems to be related to https://github.com/chjj/blessed/issues/17 :-P

**Comment by chjj** [comment]
This is where every distro should be getting the ncurses terminfo. This is it - everything:

- Terminfo source: http://invisible-island.net/ncurses/ncurses.faq.html#which_terminfo
- Compiled terminfo: http://invisible-island.net/ncurses/ncurses.faq.html#latest_version

I have no idea why ubuntu has two separate packages. That is borderline insanity. 

I'll consider adding it to the README, but it will probably sound more like me bashing Ubuntu.

**Comment by chjj** [comment]
Yeah, #17 was fixed by making the terminfo parser fallback to similarly named terminfo's if it couldn't find the terminfo corresponding to the exact $TERM value.

**Comment by chjj** [comment]
Added an FAQ explaining the ubuntu issue: https://github.com/chjj/blessed#faq

I may just include the xterm, linux, urxvt, and screen terminfos by default if they're not available.

**Comment by piranna** [comment]
Using a terminfo file it works! Sort-of... :-P

![pantallazo-qemu](https://cloud.githubusercontent.com/assets/532414/6070673/ebfe44a4-ad8e-11e4-8d55-1f0a46f8e6ed.png)

I've just only copied the terminfo for ```linux-vt``` on Ubuntu as ```linux``` and as you can see it's now drawing the lines instead of characters. They are as simple ASCII chars, but it's something! :-P Why wouldn't the Unicode glyph being used? Could it be because there's no installed a terminal Unicode font? This would explain why is using question marks for the braille dots for the map and the graphs...

Adding the info to the faq is cool, thanks! :-D Including some basic terminfos would be great :-) Don't know if they should be in blessed package or another independent one, maybe just with some ones is just enough... Only thing that you use linux-vt as basis for the linux one, since it's the one that's working ;-)

**Comment by piranna** [comment]
I'm seeing in the previous image they are being showing blocks instead of question marks for the braille dots, so seems it would not be a problem of Unicode font but more likely the terminfo is forcing to render the terminal in ASCII mode and the question mark is what it shows when don't know how to map a character, would it be?

**Comment by chjj** [comment]
@piranna, the reason neither ACS nor unicode characters are displayed works like this:

1. ACS is not supported in the terminfo. Blessed falls back to unicode chars.
2. Unicode is either not supported in the terminfo or $LANG env variable.
3. Fall back to ascii.

The linux terminfo technically supports ACS, but it is bugged. ncurses considers it bugged and so does blessed. Blessed tries to fall back to utf-8, however, if you don't have utf-8 locales compiled and do not have in in your LANG/LC_COLLATE/etc, it will fall back to ascii.

**Comment by piranna** [comment]
Ok, I don't fully understand how... but here are the lines :-P

![pantallazo-qemu-2](https://cloud.githubusercontent.com/assets/532414/6098404/bce9e26c-afdd-11e4-9f47-137d4ea0a186.png)

(The image is bigger because I managed to increase the size of the console, too ;-) ) The only thing that I did was to include the ```$LANG``` parameter as you suggested and as it's shown [here](https://docs.oracle.com/cd/E52668_01/E54669/html/ol7-kbopt.html)... but no more! Is that variable being somehow parsed? I have test it with ```en_UK.UTF-8``` and ```es_ES.UTF-8``` and worked with both, while at the same time it didn't working on my Ubuntu machine console while it was set to ```es_ES.UTF-8``` from start... :-/

Anyway, at least I't now drawing the lines :-) What I don't understand is why being this lines already on the codeset 437 and the DOS typefont, why is only using characters from the 0-127 range instead of the full ASCII extended set... Is this about being the ACS not being used in the first case, and using the in kernel [Unicode-to-codeset437](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/drivers/tty/vt/cp437.uni) conversion when the ```UTF-8``` string is defined in ```$LANG```?

I think I'll left it as is and come back later, since the current state is not so bad and my Ubuntu machine console (that I'm using as testbed) is giving me different results and state on each reboot regarding to this point :-/ The next two moves I think I'll do are to update the console font to use 512 glyphs instead of only the standard 256 ones by adding the [braille codepoints](http://yudit.org/download/fonts/UBraille/) so the graphs can be more acurate (you [can see](https://github.com/yaronn/blessed-contrib) how it should be. Unluckily there's not enought codepoints to include the glyphs used on the bar chart of bottom-left without loosing some of the other ones from the codeset 437... :-( ) and being able to have it on terminator.

There's a lof of console fonts info on [ArchLinux wiki](https://wiki.archlinux.org/index.php/Fonts#Console_fonts) and it's the main source I've followed, if you are interested :-) Oh, and thank you for being so patient with me and my questions! :-P

**Comment by chjj** [comment]
I already explained the behavior: ACS is bugged in the linux console. It can't be used. It falls back to unicode, but if unicode isn't set up properly (bad LANG value), it falls back to just ascii. It looks like you were having an issue with your LANG variable.

**Comment by chjj** [comment]
Actually, technically, if the **terminfo** (not LANG) supports utf8, blessed will fallback to unicode from ACS immediately. Either way, the linux console is falling back to unicode one reason or more.

**Comment by piranna** [comment]
> It looks like you were having an issue with your LANG variable.

Yes, in NodeOS It was not being set at all, when I set it then the lines where shown (Ubuntu has it set, but it's being ignored).


> if the terminfo (not LANG) supports utf8, blessed will fallback to unicode from ACS immediately.

Would this be done independly of having the $LANG variable defined? If so, this would be the best option...

**Comment by chjj** [comment]
It looks like there was an issue. See the above commit. It turns out, if the terminfo lacked utf8, but LANG was fine, it would fall back to ascii when that probably shouldn't happen.

You can play around with this like so:
$ NCURSES_NO_UTF8_ACS=1 node test/widget.js
$ NCURSES_NO_UTF8_ACS=1 LANG= node test/widget.js

`NCURSES_NO_UTF8_ACS=1` sets ACS to broken (the same thing that would happen if TERM=linux or if U8 is supported by the terminfo.

`LANG=` makes the LANG appear as if it does not support utf8.

**Comment by chjj** [comment]
@piranna, try the latest commit. Let me know what happens.

**Comment by chjj** [comment]
Updated the above commands. Also, setting LANG= to nothing can still end up using unicode if the terminal's U8 bool is true. In the linux console's case this is true.

**Comment by piranna** [comment]
Sorry for the delay (out of internet...), and thank you so much for your work! :-D I've been crafting a psf font with all the braille patterns and box drawing glyphs and with your latest commit now blessed-contrib demo shows awesome on my Ubuntu machine!!! :-D I'll send you a picture later ;-) I've needed to fix it to use [the latest blessed version](https://github.com/yaronn/blessed-contrib/pull/26), too. Now move it to NodeOS, compile ```setfont``` (I didn't finally get how to compile a custom font inside the Linux kernel... :-/ ) and test it there :-)

**Comment by piranna** [comment]
I'm not being able to use the font in NodeOS (```setfont``` is difficult to compile, and later didn't worked telling me a strange problem related to the font size...) and there's almost no info about how to set a custom default font compiled in the Linux kernel (and seems it's only possible for 256 glyphs fonts in codepage 437...), but as promised, here you have a screenshot of blessed-contrib demo running on a virtual terminal using my custom font... only that running on Ubuntu :-P

![20150211_010105](https://cloud.githubusercontent.com/assets/532414/6158705/668179ea-b24d-11e4-9a08-54ecf8e5118f.jpg)

I'll try to make it work on NodeOS, although I should pay some attention to my classes... Anyway, thank you so much for your time! :-)

**Comment by piranna** [comment]
Just for the record: the remaining part of this was get it to work on terminator, since I was getting a blank screen. I've decided to investigated and seems the problem was using the ```-append="console=ttyS0"``` and ```-nographic``` flags to get the NodeOS console output on terminator. After searching a bit, seems the ```-curses``` flag makes terminator itself to draw the characters instead of being done by the emulated system (NodeOS, in this case), so after changing it...

![pantallazo-5](https://cloud.githubusercontent.com/assets/532414/7332795/cd7caabe-eb52-11e4-99ea-b3f2f28d51ee.png)

...now it's working on terminator :-) I don't like the fact that don't use automatically the full terminal (I suposse it would be changed someway) and that it doesn't preserve the log the same way as it was being redirected (this is mostly the same as having a graphic window), but it's a progress :-) The thing I don't understand is why it shows the question signs if it's being drawed by ncurses and terminator... Do you have any clue what could be happening here?

**Comment by chjj** [comment]
It looks like you don't have a utf8 locale setup, but blessed thinks you do. Either that, or you just don't have a font with those unicode glyphs.

**Comment by chjj** [comment]
The latter is more likely. Because it could also mean blessed is using ACS __or__ unicode, but there's no font available for those particular unicode glyphs.

**Comment by piranna** [comment]
Sorry for the delay. I've just downloaded the blessed demos directly on my Ubuntu machine on Terminator and they are shown correctly (the time demo is drawn with vertical lines as you can see on the scheenshoot), so maybe there's an incompatibility by the fact QEmu delegates it's content to ncurses? In that case your first guest would make sense, since inside QEmu NodeOS would have a full utf8 environment, but later ncurses on the host could not be able to decode it... Or maybe in fact inside QEmu NodeOS is not totally output-agnostic, and since it doesn't have a Unicode-capable font it's already sending the question marks? How could we be able to check this kind of things? Is there any tool for this (tput.js, maybe)?

![pantallazo-7](https://cloud.githubusercontent.com/assets/532414/7401899/edf91e3a-eec7-11e4-9229-e86ff6c59a79.png)

**Comment by piranna** [comment]
I've just noticed that on QEmu with ncurses, the half-lighted characters are shown as full-lighted, so the bright (bold) bit is being ignored... Maybe it has some relationship...

**Comment by chjj** [comment]
I didn't realize you were testing inside qemu's -curses mode. You have crazy layers of stuff going on there: blessed->console->framebuffer->qemu->ncurses->terminal.

As far as I know, the -curses mode on QEMU runs the OS in VGA text mode, which would definitely limit the text output.

> I've just noticed that on QEmu with ncurses, the half-lighted characters are shown as full-lighted, so the bright (bold) bit is being ignored... Maybe it has some relationship...

The idea for making bold cells brighter came from original IBM PCs and was added as an option to XTerm eventually.

    boldColors (class ColorMode)
      Specifies  whether  to  combine  bold  attribute with colors like the IBM PC, i.e., map colors 0
      through 7 to colors 8 through 15.  These normally are the brighter versions of the first 8  col‐
      ors, hence bold.  The default is “true”.

Some terminals and consoles do not brighten bold characters, and some don't even support a bold font on top of that. That could be why.

**Comment by piranna** [comment]
> I didn't realize you were testing inside qemu's -curses mode. You have crazy layers of stuff going on there: blessed->console->framebuffer->qemu->ncurses->terminal.
> 
> As far as I know, the -curses mode on QEMU runs the OS in VGA text mode, which would definitely limit the text output.

Well, not the framebuffer layer ;-) but probably it emulates the VGA text mode :-( In fact, I need to change the ```vga=``` flag to ```extended``` to have a 80x50 terminal because the ```0x318``` is a VGA graphic mode (a 1024x768x24 framebuffer in fact, although I was using it only as a bigger console) instead of being a text mode, and QEmu show a message with the current resolution until text mode is back... so yes, probably is emulating VGA text mode using ncurses :-( VGA text mode allow to change fonts, but if the only data available from QEmu to ncurses is the VGA font keypoint and not the actual Unicode codepoint (and I think this probably is what's happening), then we'll be in a situation where NodeOS inside QEmu is converting from Unicode codepoints to it's currently loaded code page, and later and later that info is interpreted as [code page 437](http://en.wikipedia.org/wiki/Code_page_437), whatever is being used originally, so seems not only that this question marks are generated by NodeOS (code page 437 is the default one of Linux, and i didn't change it), but also things will go worse if someone try to use a diferent code page since ncurses will interpret the codepoints literally and probably you'll get garbage. Seems this is a curious edge use case... and also a road end :-(
